---
- hosts: all
  become: true
  tasks:
  - name: "Check if Ansible user exist"
    shell: cat /etc/passwd
    register: ansible_user
    ignore_errors: true
  - debug:
      var: ansible_user

  - debug: 
      msg: "ansible user exist"
    when: ('ansible' in ansible_user.stdout)

  - debug:
      msg: "ansible user doesn't exist"
    when: ('ansible' not in ansible_user.stdout)
 
  - name: "Change user password"
    user:
      name: ansible
      update_password: always
      password: "{{ mypassword|password_hash('sha512') }}"
    register: update_passwd
    when: ('ansible' in ansible_user.stdout)
  - debug:
      var: update_passwd
