---
#
# Copyright 2022
# Description: This playbook is dedicated for Telkomsel Indonesia
# For gathering all Users and Groups related to audit purpose
#

- hosts: all
  become: yes
  ignore_unreachable: yes
  any_errors_fatal: false
  gather_facts: true
  
  tasks:
  - name: "Check user"
    shell: cat /etc/passwd
    register: check_user
    ignore_errors: yes
  - debug:
      var: check_user
  
  - name: "Inform if the user exist"
    debug:
      msg: "User EXIST"
    when: ('ansible' in check_user.stdout)
  - name: "Inform if the user doesn't exist"
    debug:
      msg: "User DOESN'T exist"
    when: ('ansible' not in check_user.stdout)

  - name: "Change user password"
    user:
      name: ansible
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"
    register: update_passwd
    when: ('ansible' in check_user.stdout)
  - debug:
      var: update_passwd